# Default values for h2o-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ""
  name: h2oai/h2o-open-source-k8s
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  command: []


h2o:
  nodeCount: 1
  memoryPercentage: 50
  lookupTimeout: 180 # Three minutes by default are very generous amount of time for clustering with parallel pod management
  kubernetesApiPort: 8080


nameOverride: ""

fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

service:
  port: 80

ingress:
  enabled: false
  annotations: { }
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: [ ]
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# For reproducibility, H2O must always have the very same resources allocated throughout the whole container lifetime
resources:
  cpu: 1
  memory: 256Mi

nodeSelector: { }

volumes:
  
volumeMounts:

tolerations: [ ]

affinity: { }
